import { coreError } from '@/core/util/errors'
import { setManifestSignatureStatus, type ContentManifest } from './manifest'
import { verifyRsaSha256Signature } from './signature'
import { toByteArray } from 'base64-js'

// NOTE: We verify a canonical byte payload that is generated by the signing script.

declare function require(path: string): any

const manifest: ContentManifest = require('@/content/manifests/content.manifest.json')
const sigPayload: { publicKeyPem: string; signatureB64: string; signedBytesB64: string } | null = (() => {
  try {
    return require('@/content/manifests/content.manifest.sig.json')
  } catch {
    return null
  }
})()

function b64ToUtf8(b64: string): string {
  const bytes = toByteArray(b64)
  return new TextDecoder().decode(bytes)
}

export async function verifyContentManifestSignature(): Promise<'verified' | 'failed' | 'unsupported'> {
  if (!sigPayload) {
    setManifestSignatureStatus('failed')
    coreError('content_manifest_signature_missing', { schema: manifest.schema })
    return 'failed'
  }
  // Signed bytes include the manifest schema + entries. This prevents subtle stringify drift.
  const signedUtf8 = b64ToUtf8(sigPayload.signedBytesB64)

  const r = await verifyRsaSha256Signature({
    publicKeyPem: sigPayload.publicKeyPem,
    dataUtf8: signedUtf8,
    signatureB64: sigPayload.signatureB64,
  })

  if (!r.ok) {
    if (r.reason === 'unsupported') {
      setManifestSignatureStatus('unsupported')
      return 'unsupported'
    }
    setManifestSignatureStatus('failed')
    coreError('content_manifest_signature_invalid', { reason: r.reason, schema: manifest.schema })
    return 'failed'
  }

  setManifestSignatureStatus('verified')
  return 'verified'
}
