/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/gen-content-index.mjs
 *
 * Why: Metro bundling does not guarantee dynamic require("./" + path) works in production.
 * This map makes content imports static and deterministic.
 */

export const CONTENT_INDEX: Record<string, any> = {
  "competitions/competitions.en.json": require("./competitions/competitions.en.json"),
  "competitions/competitions.xh.json": require("./competitions/competitions.xh.json"),
  "competitions/competitions.zu.json": require("./competitions/competitions.zu.json"),
  "curriculum/phase1.en.json": require("./curriculum/phase1.en.json"),
  "curriculum/phase1.xh.json": require("./curriculum/phase1.xh.json"),
  "curriculum/phase1.zu.json": require("./curriculum/phase1.zu.json"),
  "curriculum/pro_regimen.en.json": require("./curriculum/pro_regimen.en.json"),
  "curriculum/pro_regimen.xh.json": require("./curriculum/pro_regimen.xh.json"),
  "curriculum/pro_regimen.zu.json": require("./curriculum/pro_regimen.zu.json"),
  "curriculum/pro_regimen12_advanced.en.json": require("./curriculum/pro_regimen12_advanced.en.json"),
  "curriculum/pro_regimen12_advanced.xh.json": require("./curriculum/pro_regimen12_advanced.xh.json"),
  "curriculum/pro_regimen12_advanced.zu.json": require("./curriculum/pro_regimen12_advanced.zu.json"),
  "curriculum/pro_regimen12_beginner.en.json": require("./curriculum/pro_regimen12_beginner.en.json"),
  "curriculum/pro_regimen12_beginner.xh.json": require("./curriculum/pro_regimen12_beginner.xh.json"),
  "curriculum/pro_regimen12_beginner.zu.json": require("./curriculum/pro_regimen12_beginner.zu.json"),
  "curriculum/pro_regimen12_intermediate.en.json": require("./curriculum/pro_regimen12_intermediate.en.json"),
  "curriculum/pro_regimen12_intermediate.xh.json": require("./curriculum/pro_regimen12_intermediate.xh.json"),
  "curriculum/pro_regimen12_intermediate.zu.json": require("./curriculum/pro_regimen12_intermediate.zu.json"),
  "drills/agility.en.json": require("./drills/agility.en.json"),
  "drills/agility.xh.json": require("./drills/agility.xh.json"),
  "drills/agility.zu.json": require("./drills/agility.zu.json"),
  "drills/phase1.en.json": require("./drills/phase1.en.json"),
  "drills/phase1.xh.json": require("./drills/phase1.xh.json"),
  "drills/phase1.zu.json": require("./drills/phase1.zu.json"),
  "drills/phase2.en.json": require("./drills/phase2.en.json"),
  "drills/phase2.xh.json": require("./drills/phase2.xh.json"),
  "drills/phase2.zu.json": require("./drills/phase2.zu.json"),
  "drills/warmups.en.json": require("./drills/warmups.en.json"),
  "drills/warmups.xh.json": require("./drills/warmups.xh.json"),
  "drills/warmups.zu.json": require("./drills/warmups.zu.json"),
  "guided_journey/production.en.json": require("./guided_journey/production.en.json"),
  "lessons/marketplace.en.json": require("./lessons/marketplace.en.json"),
  "lessons/marketplace.xh.json": require("./lessons/marketplace.xh.json"),
  "lessons/marketplace.zu.json": require("./lessons/marketplace.zu.json"),
  "lessons/phase1.en.json": require("./lessons/phase1.en.json"),
  "lessons/phase1.xh.json": require("./lessons/phase1.xh.json"),
  "lessons/phase1.zu.json": require("./lessons/phase1.zu.json"),
  "lessons/pro_regimen.en.json": require("./lessons/pro_regimen.en.json"),
  "lessons/pro_regimen.xh.json": require("./lessons/pro_regimen.xh.json"),
  "lessons/pro_regimen.zu.json": require("./lessons/pro_regimen.zu.json"),
  "lessons/pro_regimen12_advanced.en.json": require("./lessons/pro_regimen12_advanced.en.json"),
  "lessons/pro_regimen12_advanced.xh.json": require("./lessons/pro_regimen12_advanced.xh.json"),
  "lessons/pro_regimen12_advanced.zu.json": require("./lessons/pro_regimen12_advanced.zu.json"),
  "lessons/pro_regimen12_beginner.en.json": require("./lessons/pro_regimen12_beginner.en.json"),
  "lessons/pro_regimen12_beginner.xh.json": require("./lessons/pro_regimen12_beginner.xh.json"),
  "lessons/pro_regimen12_beginner.zu.json": require("./lessons/pro_regimen12_beginner.zu.json"),
  "lessons/pro_regimen12_intermediate.en.json": require("./lessons/pro_regimen12_intermediate.en.json"),
  "lessons/pro_regimen12_intermediate.xh.json": require("./lessons/pro_regimen12_intermediate.xh.json"),
  "lessons/pro_regimen12_intermediate.zu.json": require("./lessons/pro_regimen12_intermediate.zu.json"),
  "manifests/content.manifest.json": require("./manifests/content.manifest.json"),
  "manifests/content.manifest.sig.json": require("./manifests/content.manifest.sig.json"),
  "marketplace/coaches.en.json": require("./marketplace/coaches.en.json"),
  "marketplace/coaches.xh.json": require("./marketplace/coaches.xh.json"),
  "marketplace/coaches.zu.json": require("./marketplace/coaches.zu.json"),
  "marketplace/programs.en.json": require("./marketplace/programs.en.json"),
  "marketplace/programs.xh.json": require("./marketplace/programs.xh.json"),
  "marketplace/programs.zu.json": require("./marketplace/programs.zu.json"),
}

export function getBundledContentJson(filePath: string) {
  return CONTENT_INDEX[filePath] ?? null
}
